<?php

// default theme impementations
require_once(drupal_get_path('module', 'gsb_coveo_search') . '/theme/gsb_coveo_search.theme.inc');

/**
 * Implements hook_menu().
 */
function gsb_coveo_search_menu() {

  $access_callback = 'user_is_logged_in';
  if (!function_exists('mygsb_masquerade_get_workgroup')) {
    $access_callback = array(TRUE);
  }

  $items['coveo-search'] = array(
    'title' => 'Search',
    'page callback' => 'gsb_coveo_search_run_search',
    'access callback' => $access_callback,
    'type' => MENU_CALLBACK,
  );

  $items['coveo-search/v2/querySuggest'] = array(
    'title' => 'Search',
    'page callback' => 'gsb_coveo_search_run_querysuggest',
    'access callback' => $access_callback,
    'type' => MENU_CALLBACK,
  );

  $items['coveo-analytics'] = array(
    'title' => 'Analytics',
    'page callback' => 'gsb_coveo_search_run_analytics',
    'access callback' => $access_callback,
    'type' => MENU_CALLBACK,
  );


  $items['coveo-search-page'] = array(
    'title' => 'Search',
    'page callback' => 'gsb_coveo_search_page',
    'access callback' => $access_callback,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_page_alter().
 *
 * Adds the Coveo Page Event javascript code for tracking of all page views.
 */
function gsb_coveo_search_page_alter(&$page) {
  if (!empty($_GET['q'])) {
    if (strpos($_GET['q'], 'admin') !== false) {
      return;
    }
  }
  $module_path = drupal_get_path('module', 'gsb_coveo_search' );
  $page ['content']['#attached']['js'][] = array(
    'type'=>'file',
    'data' => 'https://static.cloud.coveo.com/coveo.analytics.js/coveoua.js'
  );
  $page ['content']['#attached']['js'][] = array(
    'type'=>'file',
    'data' => $module_path . '/js/coveo-search-page-event.js'
  );
}

/**
 * Implements hook_url_inbound_alter().
 *
 * Make search/* URL to actually behave as coveo-search-page/*.
 */
function gsb_coveo_search_url_inbound_alter(&$path, $original_path, $path_language) {
  // This will not allow us to use search module, it will redirect to coveo instead.
  if (arg(0, $path) == 'search') {
    $path = 'coveo-search-page/' . arg(1, $path);
  }
}

/**
 * Implements hook_url_outbound_alter().
 *
 * Make coveo-search-page/* links to go to search/* URL.
 */
function gsb_coveo_search_url_outbound_alter(&$path, &$options, $original_path) {
  if (arg(0, $path) == 'coveo-search-page') {
    $path = str_replace('coveo-search-page', 'search', $path);
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function gsb_coveo_search_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'menu') {
    $group = $implementations['gsb_coveo_search'];
    unset($implementations['gsb_coveo_search']);
    $implementations['gsb_coveo_search'] = $group;
  }
}

/**
 * Implements hook_block_info().
 */
function gsb_coveo_search_block_info() {
  $blocks = array();

  // block search form
  $blocks['coveo_search_block_form'] = array(
    'info' => t('Coveo search form'),
    'cache' => DRUPAL_NO_CACHE,
  );

  // block search suggests form
  $blocks['coveo_search_block_suggests_form'] = array(
    'info' => t('Coveo search suggests form'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function gsb_coveo_search_block_view($delta = '') {

  $block = array();

  if (true) { //user_access('access_google_appliance_content')) {
    switch ($delta) {
      case 'coveo_search_block_form':
        $block['content'] = drupal_get_form('coveo_search_block_form');
        break;
      case 'coveo_search_block_suggests_form':
        $block['content'] = drupal_get_form('coveo_search_block_suggests_form');
        break;
    }
  }

  return $block;
}

/**
 * Form builder outputs the search form for the search block
 *
 * @ingroup forms
 * @see coveo_search_block_form_submit()
 * @see coveo-search-block-form.tpl.php
 */
function coveo_search_block_form($form, &$form_state) {

  $form['search_keys'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter the terms you wish to search for.'),
    '#title_display' => 'invisible',
    '#size' => 15,
    '#default_value' => '',
  );

  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Search'),
    ),
  );

  return $form;
}

/**
 * Submit handler for block search form just sets the redirect for the form
 * based on the search query
 */
function coveo_search_block_form_submit($form, &$form_state) {
  global $base_url;

  // kill any dynamic destinations, as the results page is always the destination
  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
  }

  // set the redirect
  $search_query = rawurlencode($form_state['values']['search_keys']);
  $form_state['redirect'] = url($base_url . '/search#q=' . $search_query, array('absolute' => TRUE));
  // search execution happens in page callback
}

/**
 * Form builder outputs the search form for the search block
 *
 * @ingroup forms
 * @see coveo_search_block_suggests_form_submit()
 * @see coveo-search-block-suggests-form.tpl.php
 */
function coveo_search_block_suggests_form($form, &$form_state) {
  global $base_url;

  $form['search_keys'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter the terms you wish to search for.'),
    '#title_display' => 'invisible',
    '#size' => 15,
    '#default_value' => '',
  );

  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Search'),
    ),
  );

  return $form;
}

/**
 * Submit handler for block search form just sets the redirect for the form
 * based on the search query
 */
function coveo_search_block_suggests_form_submit($form, &$form_state) {
  global $base_url;

  // kill any dynamic destinations, as the results page is always the destination
  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
  }

  // set the redirect
  $search_query = urlencode($form_state['values']['search_keys']);
  $form_state['redirect'] = url($base_url . '/search#q=' . $search_query, array('absolute' => TRUE));
  // search execution happens in page callback
}

/**
 * Displays Search Page using Coveo template
 */
function gsb_coveo_search_page() {
  global $base_url;

  $search_query = '';

  drupal_add_css('https://static.cloud.coveo.com/searchui/v2.3826/css/CoveoFullSearchNewDesign.css', 'external');

  drupal_add_css(drupal_get_path('module', 'gsb_coveo_search') . '/css/coveo-search-custom.css');

  drupal_add_js('https://static.cloud.coveo.com/searchui/v2.3826/js/CoveoJsSearch.min.js', 'external');
  drupal_add_js('https://static.cloud.coveo.com/searchui/v2.3826/js/templates/templatesNew.js', 'external');

  drupal_add_js(drupal_get_path('module', 'gsb_coveo_search') . '/js/coveo-search-page.js');

  drupal_add_js(array('gsb_coveo_search_page' => array('search_query' => $search_query, 'coveo_debug' => 'false')), 'setting');
  drupal_add_js(array('baseUrl' => $base_url), 'setting');

  $template_data = array();

  $pos = strpos($base_url, 'mygsb');
  if ($pos === false) {
    return theme('coveo_search_page', $template_data);
  }
  else {
    return theme('coveo_mygsb_search_page', $template_data);
  }
}

/**
 * Proxy for posting query suggestions
 */
function gsb_coveo_search_run_querysuggest() {

  list($pipeline, $audience, $contextAudience) = gsb_coveo_search_get_filter_info();

  $source = gsb_coveo_search_get_source_info($pipeline);

  $data = $_POST;

  $search = $_POST['q'];

  $data["q"] = $search;
  $data["cq"] = $source . " AND " . $audience;

  $data["pipeline"] = $pipeline;
  $data["searchHub"] = $pipeline;

  $data["customData"] = array(
    "context" => array(
      "context_audience" => $contextAudience
    )
  );

  unset($data['coveoquery']);
  unset($data['actionsHistory']);
  unset($data['fieldsToInclude']);

  $data['queryFunctions'] = array();
  $data['rankingFunctions'] = array();
  $data['groupBy'] = array();

  $query_data = json_encode($data);

  $apikey = variable_get("coveo_api_key");
  $apikey = str_replace("access_token=","", $apikey);
  $bearer = "Bearer " . $apikey;

  $options = array(
    'method' => 'POST',
    'data' => $query_data,
    'timeout' => 15,
    'headers' => array('Content-Type' => 'application/json', 'Authorization' => $bearer),
  );

  $url = variable_get('coveo_search_endpoint', '');
  $url .= "querySuggest";
  $url .= "?";
  $url .= variable_get("coveo_api_key");
  $url .= "&";
  $url .= variable_get("coveo_organization_id");

  $url = str_replace("platform.cloud.coveo.com","search.cloud.coveo.com", $url);

  $result = drupal_http_request($url, $options);

  if (empty($result->data)) {
    return;
  }

  drupal_add_http_header('Content-Type', 'application/json');

  echo $result->data;
  drupal_exit();
}

/**
 * Proxy for posting search queries
 */
function gsb_coveo_search_run_search() {

  if (!empty($_GET['q']) && strpos($_GET['q'], 'subscriptions')) {
    return;
  }

  list($pipeline, $audience, $contextAudience) = gsb_coveo_search_get_filter_info();

  $source = gsb_coveo_search_get_source_info($pipeline);

  if (!empty($_POST['patternType'])) {
    $data = $_POST;
    $data['pipeline'] = $pipeline;
    if (!empty($data['queryOverride'])) {
      if ($pipeline == "gsb-pipeline") {
        $data['queryOverride'] = "@source=('Stanford GSB public')";
      }
    }
    unset($data['sortCriteria']);
  }
  else {
    if (empty($_POST['q'])) {
      $search = '';
    }
    else {
      $search = $_POST['q'];
    }

    $data = $_POST;

    $data["q"] = $search;
    $data["cq"] = $source . " AND " . $audience;

    // todo: The following line was needed to get the 'Faculty' facet working on Public web site.
    // All other facets seemed to work fine.
    // This has been raised as an issue with Coveo support.
    //unset($data["enableDuplicateFiltering"]);
    $data["enableDuplicateFiltering"] = true;

    $data["pipeline"] = $pipeline;
    $data["searchHub"] = $pipeline;

    $data["customData"] = array(
      "context" => array(
        "context_audience" => $contextAudience
      )
    );

    unset($data['actionsHistory']);
    unset($data['fieldsToInclude']);

    $data['queryFunctions'] = array();
    $data['rankingFunctions'] = array();

    // If on MyGSB site
    if (function_exists('mygsb_masquerade_get_workgroup')) {
      // add groupBy/facet for @source
      $data['groupBy'] = array(
        array(
          'field' => '@source',
          'maximumNumberOfValues' => 9,
          'sortCriteria' => 'occurrences',
          'injectionDepth' => 1000,
          'allowedValues' => array(
             'mygsb website',
             'stanford gsb public',
             'stanford gsb youtube',
             'gsb events',
             'stanford events'
          )
        ),
        array(
          'field' => '@department',
          'maximumNumberOfValues' => 9,
          'sortCriteria' => 'occurrences',
          'injectionDepth' => 1000
        )
      );
    }
    else {
      $data['groupBy'] = array();
      // todo: We may be adding this back in a future release
      // add groupBy/facet for @content_type
      /*
      $data['groupBy'] = array(
        array(
          'field' => '@content_type',
          'maximumNumberOfValues' => 9,
          'sortCriteria' => 'occurrences',
          'injectionDepth' => 1000
        )
      );
      */
    }
  }

  $query_data = json_encode($data);

  $options = array(
    'method' => 'POST',
    'data' => $query_data,
    'timeout' => 15,
    'headers' => array('Content-Type' => 'application/json'),
  );

  $url = variable_get('coveo_search_endpoint', '');
  if (!empty($_POST['patternType'])) {
    $url .= "values";
  }
  $url .= "?";
  $url .= variable_get("coveo_api_key");
  $url .= "&";
  $url .= variable_get("coveo_organization_id");

  $pattern = "";
  if (!empty($_POST['pattern']))
  {
    $pattern = $_POST['pattern'];
  }

  $result = drupal_http_request($url, $options);

  if (empty($result->data)) {
    return;
  }

  drupal_add_http_header('Content-Type', 'application/json');

  echo $result->data;
  drupal_exit();
}

/**
 * Proxy for posting analytics data
 */
function gsb_coveo_search_run_analytics() {

  $received_json = file_get_contents("php://input",  TRUE);
  $json = drupal_json_decode($received_json, TRUE);

  if (!empty($json[0])) {
    $data = $json[0];
  }
  else if (!empty($json)) {
    $data = $json;
  }
  else {
    return;
  }

  list($pipeline, $audience) = gsb_coveo_search_get_filter_info();

  if (empty($data['customData'])) {
    $data["customData"] = array(
      "context" => array(
        "context_audience" => $audience
      )
    );
  }
  else {
    $data["customData"]["context"] = array("context_audience" => $audience);
  }
  
  // set the searchHub (originLevel1) to the pipeline name
  $data["originLevel1"] = $pipeline;

  $analytics_data = json_encode($data);

  $options = array(
    'method' => 'POST',
    'data' => $analytics_data,
    'timeout' => 15,
    'headers' => array('Content-Type' => 'application/json'),
  );

  $url = variable_get('coveo_analytics_endpoint', '');
  $url .= "/rest/v15/analytics/search";

  if (!empty($_GET['q']) && strpos($_GET['q'], 'analytics/click') > 0) {
    $url = str_replace('analytics/search', 'analytics/click', $url);
  }
  if (!empty($_GET['q']) && strpos($_GET['q'], 'analytics/custom') > 0) {
    $url = str_replace('analytics/search', 'analytics/custom', $url);
  }

  $url .= "?";
  $url .= variable_get("coveo_api_key");
  $url .= "&";
  $url .= variable_get("coveo_organization_id");

  $result = drupal_http_request($url, $options);

  drupal_add_http_header('Content-Type', 'application/json');
  echo $result->data;
  drupal_exit();
}

/**
 * Returns pipeline and audience filter settings for user
 */
function gsb_coveo_search_get_filter_info() {
  global $user;

  $pipeline = "gsb-pipeline";
  $audience = "@gsbaudience=('public')";
  $contextAudience = "public";

  // todo: Deferred

  if (function_exists('mygsb_masquerade_get_workgroup')) {

    $pipeline = "mygsb-pipeline";

    $workgroup = mygsb_masquerade_get_workgroup($user);

    switch ($workgroup) {
      case 'MBA Admit Round 1':
        $audience = "(@gsbaudience=('MyGSBDrupal_mbaadmitround1','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_mbaadmitround1';
        break;
      case 'MBA Admit Round 2':
        $audience = "(@gsbaudience=('MyGSBDrupal_mbaadmitround2','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_mbaadmitround2';
        break;
      case 'MBA Admit Round 3':
        $audience = "(@gsbaudience=('MyGSBDrupal_mbaadmitround3','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_mbaadmitround3';
        break;
      case 'MBA plus':
        $audience = "(@gsbaudience=('MyGSBDrupal_mbaplus','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_mbaplus';
        break;
      case 'MBA1':
        $audience = "(@gsbaudience=('MyGSBDrupal_mba1','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_mba1';
        break;
      case 'MBA2':
        $audience = "(@gsbaudience=('MyGSBDrupal_mba2','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_mba2';
        break;
      case 'MSx':
        $audience = "(@gsbaudience=('MyGSBDrupal_msx','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_msx';
        break;
      case 'MSx Admit':
        $audience = "(@gsbaudience=('MyGSBDrupal_msxadmit','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_msxadmit';
        break;
      case 'PhD':
        $audience = "(@gsbaudience=('MyGSBDrupal_phd','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_phd';
        break;
      case 'PhD Admit':
        $audience = "(@gsbaudience=('MyGSBDrupal_phdadmit','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_phdadmit';
        break;
      case 'Faculty':
        $audience = "(@gsbaudience=('MyGSBDrupal_faculty','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_faculty';
        break;
      case 'Staff':
        $audience = "(@gsbaudience=('MyGSBDrupal_staff','public','MyGSBDrupal_gen') OR NOT @gsbaudience)";
        $contextAudience = 'MyGSBDrupal_staff';
        break;
    }
  }

  return array ($pipeline, $audience, $contextAudience);
}

/**
 * Returns source info
 */
function gsb_coveo_search_get_source_info($pipeline) {

  $public_source = "GSB public website";
  $mygsb_source  = "MyGSB website";
  $gsb_events = "GSB Events";
  $stanford_events = "Stanford Events";
  $stanford_youtube = "Stanford GSB YouTube";

  $sandbox_testing = false;

  if ($sandbox_testing) {
    $public_source = "Stanford GSB public";
    $mygsb_source  = "MyGSB website";
  }

  $source = "(" 
            . "@source=(" . '"' . $public_source . '"' . ")" . " OR " 
            . "@source=(" . '"' . $stanford_events . '"' . ")" . " OR " 
            . "@source=(" . '"' . $gsb_youtube . '"' . ")" . 
          ")";
  if ($pipeline == 'mygsb-pipeline') {
    $source = "(" 
              . "@source=(" . '"' . $public_source . '"' . ")" . " OR " 
              . "@source=(" . '"' . $mygsb_source . '"' . ")" . " OR " 
              . "@source=(" . '"' . $gsb_events . '"' . ")" . " OR " 
              . "@source=(" . '"' . $stanford_events . '"' . ")" . " OR " 
              . "@source=(" . '"' . $stanford_youtube . '"' . ")" . 
          ")";
  }

  return $source;
}
